<a href="https://colab.research.google.com/github/narame7/UOS-FootballDataAnalytics-Tutorial/blob/main/%EC%B6%95%EA%B5%AC_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_2%EA%B0%95_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 통계 데이터 크롤링

In [1]:
!pip install ScraperFC

Requirement already satisfied: ScraperFC in /usr/local/lib/python3.12/dist-packages (3.4.0)
Requirement already satisfied: botasaurus>=4.0.76 in /usr/local/lib/python3.12/dist-packages (from ScraperFC) (4.0.88)
Requirement already satisfied: bs4>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from ScraperFC) (0.0.2)
Requirement already satisfied: cloudscraper>=1.2.71 in /usr/local/lib/python3.12/dist-packages (from ScraperFC) (1.2.71)
Requirement already satisfied: datetime>=5.5 in /usr/local/lib/python3.12/dist-packages (from ScraperFC) (5.5)
Requirement already satisfied: lxml>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from ScraperFC) (5.4.0)
Requirement already satisfied: numpy>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from ScraperFC) (2.0.2)
Requirement already satisfied: pandas>=2.2.3 in /usr/local/lib/python3.12/dist-packages (from ScraperFC) (2.3.2)
Requirement already satisfied: requests>=2.32.3 in /usr/local/lib/python3.12/dist-packages (from ScraperFC) (2.32.4)
Requirement already satisfied: selenium>=4.28.1 in /usr/local/lib/python3.12/dist-packages (from ScraperFC) (4.35.0)
Requirement already satisfied: tqdm>=4.67.1 in /usr/local/lib/python3.12/dist-packages (from ScraperFC) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from botasaurus>=4.0.76->ScraperFC) (5.9.5)
Requirement already satisfied: javascript-fixes in /usr/local/lib/python3.12/dist-packages (from botasaurus>=4.0.76->ScraperFC) (1.1.29)
Requirement already satisfied: joblib>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from botasaurus>=4.0.76->ScraperFC) (1.5.2)
Requirement already satisfied: beautifulsoup4>=4.11.2 in /usr/local/lib/python3.12/dist-packages (from botasaurus>=4.0.76->ScraperFC) (4.13.5)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (from botasaurus>=4.0.76->ScraperFC) (3.1.5)
Requirement already satisfied: close-chrome in /usr/local/lib/python3.12/dist-packages (from botasaurus>=4.0.76->ScraperFC) (4.0.40)
Requirement already satisfied: botasaurus-humancursor in /usr/local/lib/python3.12/dist-packages (from botasaurus>=4.0.76->ScraperFC) (4.0.83)
Requirement already satisfied: botasaurus-api in /usr/local/lib/python3.12/dist-packages (from botasaurus>=4.0.76->ScraperFC) (4.0.10)
Requirement already satisfied: botasaurus-driver in /usr/local/lib/python3.12/dist-packages (from botasaurus>=4.0.76->ScraperFC) (4.0.91)
Requirement already satisfied: bota in /usr/local/lib/python3.12/dist-packages (from botasaurus>=4.0.76->ScraperFC) (4.0.154)
Requirement already satisfied: botasaurus-proxy-authentication in /usr/local/lib/python3.12/dist-packages (from botasaurus>=4.0.76->ScraperFC) (1.0.16)
Requirement already satisfied: botasaurus-requests in /usr/local/lib/python3.12/dist-packages (from botasaurus>=4.0.76->ScraperFC) (4.0.38)
Requirement already satisfied: pyparsing>=2.4.7 in /usr/local/lib/python3.12/dist-packages (from cloudscraper>=1.2.71->ScraperFC) (3.2.3)
Requirement already satisfied: requests-toolbelt>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from cloudscraper>=1.2.71->ScraperFC) (1.0.0)
Requirement already satisfied: zope.interface in /usr/local/lib/python3.12/dist-packages (from datetime>=5.5->ScraperFC) (7.2)
Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (from datetime>=5.5->ScraperFC) (2025.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.3->ScraperFC) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.3->ScraperFC) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.3->ScraperFC) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.3->ScraperFC) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.3->ScraperFC) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.3->ScraperFC) (2025.8.3)
Requirement already satisfied: trio~=0.30.0 in /usr/local/lib/python3.12/dist-packages (from selenium>=4.28.1->ScraperFC) (0.30.0)
Requirement already satisfied: trio-websocket~=0.12.2 in /usr/local/lib/python3.12/dist-packages (from selenium>=4.28.1->ScraperFC) (0.12.2)
Requirement already satisfied: typing_extensions~=4.14.0 in /usr/local/lib/python3.12/dist-packages (from selenium>=4.28.1->ScraperFC) (4.14.1)
Requirement already satisfied: websocket-client~=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium>=4.28.1->ScraperFC) (1.8.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.2->botasaurus>=4.0.76->ScraperFC) (2.8)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.2.3->ScraperFC) (1.17.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio~=0.30.0->selenium>=4.28.1->ScraperFC) (25.3.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from trio~=0.30.0->selenium>=4.28.1->ScraperFC) (2.4.0)
Requirement already satisfied: outcome in /usr/local/lib/python3.12/dist-packages (from trio~=0.30.0->selenium>=4.28.1->ScraperFC) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio~=0.30.0->selenium>=4.28.1->ScraperFC) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.12/dist-packages (from trio-websocket~=0.12.2->selenium>=4.28.1->ScraperFC) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.5.0->selenium>=4.28.1->ScraperFC) (1.7.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from bota->botasaurus>=4.0.76->ScraperFC) (8.2.1)
Requirement already satisfied: deprecated in /usr/local/lib/python3.12/dist-packages (from botasaurus-driver->botasaurus>=4.0.76->ScraperFC) (1.2.18)
Requirement already satisfied: pyvirtualdisplay in /usr/local/lib/python3.12/dist-packages (from botasaurus-driver->botasaurus>=4.0.76->ScraperFC) (3.0)
Requirement already satisfied: pytweening in /usr/local/lib/python3.12/dist-packages (from botasaurus-humancursor->botasaurus>=4.0.76->ScraperFC) (1.2.0)
Requirement already satisfied: httpx in /usr/local/lib/python3.12/dist-packages (from botasaurus-requests->botasaurus>=4.0.76->ScraperFC) (0.28.1)
Requirement already satisfied: geventhttpclient in /usr/local/lib/python3.12/dist-packages (from botasaurus-requests->botasaurus>=4.0.76->ScraperFC) (2.3.4)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from botasaurus-requests->botasaurus>=4.0.76->ScraperFC) (13.9.4)
Requirement already satisfied: gevent in /usr/local/lib/python3.12/dist-packages (from botasaurus-requests->botasaurus>=4.0.76->ScraperFC) (25.8.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl->botasaurus>=4.0.76->ScraperFC) (2.0.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from zope.interface->datetime>=5.5->ScraperFC) (80.9.0)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket~=0.12.2->selenium>=4.28.1->ScraperFC) (0.16.0)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.12/dist-packages (from deprecated->botasaurus-driver->botasaurus>=4.0.76->ScraperFC) (1.17.3)
Requirement already satisfied: greenlet>=3.2.2 in /usr/local/lib/python3.12/dist-packages (from gevent->botasaurus-requests->botasaurus>=4.0.76->ScraperFC) (3.2.4)
Requirement already satisfied: zope.event in /usr/local/lib/python3.12/dist-packages (from gevent->botasaurus-requests->botasaurus>=4.0.76->ScraperFC) (5.1.1)
Requirement already satisfied: brotli in /usr/local/lib/python3.12/dist-packages (from geventhttpclient->botasaurus-requests->botasaurus>=4.0.76->ScraperFC) (1.1.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx->botasaurus-requests->botasaurus>=4.0.76->ScraperFC) (4.10.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx->botasaurus-requests->botasaurus>=4.0.76->ScraperFC) (1.0.9)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->botasaurus-requests->botasaurus>=4.0.76->ScraperFC) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->botasaurus-requests->botasaurus>=4.0.76->ScraperFC) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->botasaurus-requests->botasaurus>=4.0.76->ScraperFC) (0.1.2)

In [2]:
import sys
sys.path.append("../src")
import pandas as pd
import ScraperFC as sfc

## 필요한 라이브러리 import

## [ClubElo](http://clubelo.com/)
- 팀들의 역대 Elo 점수를 알 수 있는 사이트.

In [3]:
ce = sfc.ClubElo()
ce.scrape_team_on_date('Tottenham', '2023-08-13')

np.float64(1815.88818359)

 ## [FBref](https://fbref.com/en/)
- 팀과 선수의 세부적인 기록을 가장 자세히 제공하는 사이트.

In [4]:
fb = sfc.FBref()

In [5]:
# valid_league = [
#     'Copa Libertadores', 'Champions League', 'Europa League', 'Europa Conference League',
#     'World Cup', 'Copa America', 'Euros', 'Big 5 combined', 'EPL',
#     'Ligue 1', 'Bundesliga', 'Serie A', 'La Liga', 'MLS', 'Brazilian Serie A',
#     'Eredivisie', 'Liga MX', 'Primeira Liga', 'Belgian Pro League', 'Argentina Liga Profesional',
#     'Saudi Pro League', 'Turkish Super Lig', 'EFL Championship', 'La Liga 2', '2. Bundesliga',
#     'Ligue 2', 'Serie B', 'Womens Champions League', 'Womens World Cup',
#     'Womens Euros', 'NWSL', 'A-League Women', 'WSL', 'D1 Feminine',
#     'Womens Bundesliga', 'Womens Serie A', 'Liga F', 'NWSL Challenge Cup', 'NWSL Fall Series'
# ]

### 리그 순위 불러오기

In [6]:
league = fb.scrape_league_table('2025-2026', 'EPL')

In [7]:
league[0]

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper,Notes
0,1,Liverpool,3,3,0,0,8,4,4,9,3.00,3.4,3.2,0.2,0.08,W W W,60385,Hugo Ekitike - 2,Alisson,NaN
1,2,Chelsea,3,2,1,0,7,1,6,7,2.33,6.4,2.3,4.1,1.38,D W W,39712,"João Pedro, Enzo Fernández - 2",Robert Sánchez,NaN
2,3,Arsenal,3,2,0,1,6,1,5,6,2.00,4.4,2.2,2.2,0.75,W W L,60110,"Viktor Gyökeres, Jurriën Timber - 2",David Raya,NaN
3,4,Tottenham,3,2,0,1,5,1,4,6,2.00,3.6,4.0,-0.4,-0.13,W W L,61164,"Richarlison, Brennan Johnson - 2",Guglielmo Vicario,NaN
4,5,Everton,3,2,0,1,5,3,2,6,2.00,4.3,5.5,-1.2,-0.41,L W W,51759,Iliman Ndiaye - 2,Jordan Pickford,NaN
5,6,Sunderland,3,2,0,1,5,3,2,6,2.00,3.0,2.8,0.3,0.10,W L W,46250,Wilson Isidor - 2,Robin Roefs,NaN
6,7,Bournemouth,3,2,0,1,4,4,0,6,2.00,4.5,2.9,1.7,0.55,L W W,11070,Antoine Semenyo - 2,Đorđe Petrović,NaN
7,8,Crystal Palace,3,1,2,0,4,1,3,5,1.67,4.4,3.6,0.8,0.27,D D W,24876,Ismaila Sarr - 2,Dean Henderson,NaN
8,9,Manchester Utd,3,1,1,1,4,4,0,4,1.33,6.7,4.3,2.4,0.82,L D W,73866,"Bruno Fernandes, Bryan Mbeumo - 1",Altay Bayındır,NaN
9,10,Nott'ham Forest,3,1,1,1,4,5,-1,4,1.33,3.5,4.9,-1.5,-0.49,W D L,30082,Chris Wood - 2,Matz Sels,NaN
10,11,Brighton,3,1,1,1,3,4,-1,4,1.33,6.1,4.1,2.0,0.65,D L W,31482,"James Milner, Matt O'Riley... - 1",Bart Verbruggen,NaN
11,12,Leeds United,3,1,1,1,1,5,-4,4,1.33,2.9,3.9,-1.0,-0.34,W L D,36774,Lukas Nmecha - 1,Lucas Perri,NaN
12,13,Manchester City,3,1,0,2,5,4,1,3,1.00,5.8,3.9,1.9,0.62,W L L,51785,Erling Haaland - 3,James Trafford,NaN
13,14,Burnley,3,1,0,2,4,6,-2,3,1.00,3.1,6.6,-3.6,-1.18,L W L,21285,Jaidon Anthony - 2,Martin Dúbravka,NaN
14,15,Brentford,3,1,0,2,3,5,-2,3,1.00,3.8,4.5,-0.7,-0.24,L W L,16838,Thiago - 2,Caoimhín Kelleher,NaN
15,16,West Ham,3,1,0,2,4,8,-4,3,1.00,3.7,4.2,-0.5,-0.17,L L W,62462,Lucas Paquetá - 2,Mads Hermansen,NaN
16,17,Newcastle Utd,3,0,2,1,2,3,-1,2,0.67,2.9,1.6,1.3,0.43,D L D,52230,"Bruno Guimarães, William Osula - 1",Nick Pope,NaN
17,18,Fulham,3,0,2,1,2,4,-2,2,0.67,3.4,5.2,-1.8,-0.60,D D L,27512,"Emile Smith Rowe, Rodrigo Muniz - 1",Bernd Leno,NaN
18,19,Aston Villa,3,0,1,2,0,4,-4,1,0.33,2.5,5.3,-2.8,-0.93,D L L,41781,NaN,Marco Bizot,NaN
19,20,Wolves,3,0,0,3,2,8,-6,0,0.00,2.1,5.6,-3.5,-1.16,L L L,30864,"Hwang Hee-chan, Rodrigo Gomes - 1",José Sá,NaN

### 경기 정보 불러오기

In [8]:
links = fb.get_match_links('2025-2026', 'EPL') # 경기 링크 불러오기
match = fb.scrape_match(links[3]) # 불러온 링크 적용하기

In [9]:
match

,Link,Date,Stage,Home Team,Away Team,Home Team ID,Away Team ID,Home Goals,Away Goals,Home Player Stats,Away Player Stats,Shots
0,https://fbref.com/en/matches/2dbd7fbd/Chelsea-...,"Saturday August 30, 2025",Premier League (Matchweek 3),Chelsea,Fulham,cff3d9bb,fd962109,2,0,Summary Unnamed: 0_level_0 Unnamed...,Summary Unnamed: 0_level_0 Unnamed...,Both Unnamed: 0_level_0 Unnamed: 1_le...

In [10]:
match.loc[0,'Away Player Stats']['Summary'].head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
              Player                  #             Nation                Pos
0      Rodrigo Muniz                9.0             br BRA                 FW
1       Raúl Jiménez                7.0             mx MEX                 FW
2         Alex Iwobi               17.0             ng NGA                 LW
3       Adama Traoré               11.0             es ESP                 RW
4   Timothy Castagne               21.0             be BEL                 RW

  Unnamed: 4_level_0 Unnamed: 5_level_0 Performance               ... SCA      \
                 Age                Min         Gls Ast PK PKatt  ... SCA GCA
0             24-118                 59           0   0  0     0  ...   0   0
1             34-117                 31           0   0  0     0  ...   1   0
2             29-119                 83           0   0  0     0  ...   0   0
3             29-217                  7           0   0  0     0  ...   1   0
4             29-268                 59           0   0  0     0  ...   3   0

  Passes                Carries      Take-Ons
     Cmp Att  Cmp% PrgP Carries PrgC      Att Succ
0      2  10  20.0    1      11    0        1    0
1      6   8  75.0    2       7    0        2    0
2     36  49  73.5    8      46    6        1    0
3      7   9  77.8    0       6    2        0    0
4     12  18  66.7    1      12    0        1    0

[5 rows x 31 columns]

### 특정 경기의 슈팅 창출 순위 구하기

In [11]:
def flatten_columns(df):
    df = df.copy()
    new_cols = []
    for col in df.columns.to_flat_index():
        upper, lower = col
        if "Unnamed" in str(upper):
            # 위쪽 이름이 없으면 아래쪽만 사용
            new_cols.append(lower)
        else:
            new_cols.append(f"{upper}_{lower}")


    df.columns = new_cols
    df = df[~df['Player'].str.contains("Players", na=False)].copy()
    return df

home_df = match.loc[0,'Home Player Stats']['Summary']
away_df = match.loc[0,'Away Player Stats']['Summary']
home = flatten_columns(home_df)
away = flatten_columns(away_df)

rename_map = {
    'Performance_Sh': 'Shots',
    'SCA_SCA': 'SCA',
    'SCA_GCA': 'GCA',
    'Performance_Min': 'Min',
    'Expected_xG': 'xG',
    'Passes_PrgP': 'Progressive Pass'
}
home = home.rename(columns=rename_map)
away = away.rename(columns=rename_map)

all_players = pd.concat([home, away], ignore_index=True)
all_players['SCA'] = pd.to_numeric(all_players['SCA'], errors='coerce')
all_players_sorted = all_players.sort_values('SCA', ascending=False)

keep_cols = [c for c in ['Player', 'Team', 'Pos', 'Age', 'Min','Shots', 'xG', 'Progressive Pass', 'SCA', 'GCA'] if c in all_players_sorted.columns]
all_players_sorted[keep_cols].head(15)

,Player,Pos,Age,Min,Shots,xG,Progressive Pass,SCA,GCA
3,Pedro Neto,"LW,RW",25-174,80,0,0.0,4,4,0
24,Saša Lukić,DM,29-017,90,0,0.0,3,4,0
13,Malo Gusto,"RB,RW",22-103,90,0,0.0,5,3,0
19,Timothy Castagne,RW,29-268,59,1,0.1,1,3,0
28,Joachim Andersen,CB,29-091,90,2,0.2,2,3,0
9,Moisés Caicedo,DM,23-301,90,1,0.1,5,2,1
5,Estêvão Willian,RW,18-128,67,1,0.4,1,2,0
12,Trevoh Chalobah,CB,26-056,90,3,0.1,3,2,0
10,Marc Cucurella,LB,27-039,90,0,0.0,8,2,0
8,Enzo Fernández,DM,24-225,90,0,0.8,3,2,1
1,Tyrique George,FW,19-207,67,1,0.2,1,2,1
26,Antonee Robinson,LB,28-022,24,0,0.0,2,2,0
7,João Pedro,"AM,FW",23-338,90,3,0.7,4,1,0
2,Andrey Santos,AM,21-119,10,0,0.0,1,1,0
21,Joshua King,AM,18-239,66,1,0.0,2,1,0

## [Understat](https://understat.com/)

- 자체 xG 모델과 여러 기록이 있는 통계 사이트

In [12]:
us = sfc.Understat()

### 링크 불러오기

In [13]:
us_match_links = us.get_match_links('2025/2026', 'EPL')
us_season_links = us.get_season_link('2025/2026', 'EPL')
us_team_links = us.get_team_links('2025/2026', 'EPL')

### 팀 순위 보기

In [14]:
tables = us.scrape_league_tables('2024/2025', 'EPL')

In [15]:
tables[0] # 전체 순위, 홈 경기 순위, 원정 경기 순위

,Team,M,W,D,L,G,GA,PTS,xG,NPxG,xGA,NPxGA,NPxGD,PPDA,OPPDA,DC,ODC,xPTS
0,Liverpool,38,25,9,4,86,41,84,93.239341,86.388831,42.320521,40.661526,45.727305,8.936354,16.000000,442,200,81.8437
1,Arsenal,38,20,14,4,69,34,74,73.569905,72.047565,39.979862,37.696349,34.351216,8.797847,14.311111,366,156,72.9622
2,Manchester City,38,21,8,9,72,44,71,73.148430,70.103760,52.903197,49.858519,20.245241,12.088983,17.078582,431,198,64.6631
3,Chelsea,38,20,9,9,64,43,69,73.117289,69.311449,54.262188,49.695179,19.616270,10.840295,13.983439,337,226,62.5617
4,Aston Villa,38,19,9,10,58,51,66,66.385246,61.710806,54.998103,52.714603,8.996203,12.388811,9.955724,285,248,61.5269
5,Newcastle United,38,20,6,12,68,47,66,71.482065,66.915061,53.977216,52.454874,14.460187,10.276413,10.838337,349,232,62.6107
6,Nottingham Forest,38,19,8,11,58,46,65,52.749253,50.465744,55.917692,53.634183,-3.168439,14.215297,8.226287,220,271,50.0071
7,Brighton,38,16,13,9,66,59,61,65.276870,59.948684,59.123991,52.273469,7.675215,9.933128,12.555975,322,243,57.2635
8,Brentford,38,16,8,14,66,57,56,67.119797,62.552775,60.864798,60.103628,2.449147,10.869624,12.144886,278,394,54.9392
9,Bournemouth,38,15,11,12,58,46,56,72.620869,67.292682,53.993587,50.948906,16.343776,8.530938,9.791610,283,327,65.0254
10,Fulham,38,15,9,14,54,54,54,58.003414,54.958735,49.232539,46.187863,8.770872,12.100000,13.069241,232,226,57.6028
11,Crystal Palace,38,13,14,11,51,51,53,67.780770,64.736094,58.884335,57.361995,7.374099,13.171429,9.024970,243,270,58.1567
12,Everton,38,11,15,12,42,44,48,46.869415,45.347074,53.663086,52.140756,-6.793682,14.283375,8.983247,186,267,47.6514
13,West Ham,38,11,10,17,46,62,43,50.589050,48.305540,68.087568,65.804062,-17.498522,12.252324,10.109489,224,316,41.7600
14,Manchester United,38,11,9,18,44,54,42,56.911310,53.866651,60.727510,57.633397,-3.766746,10.068104,13.258809,309,218,52.2395
15,Wolverhampton Wanderers,38,12,6,20,54,69,42,45.370551,45.370551,61.572156,54.721656,-9.351105,11.535499,9.923323,215,284,41.4533
16,Tottenham,38,11,5,22,64,65,38,65.363487,62.318816,68.230997,65.947487,-3.628671,9.431302,10.225510,316,280,50.0654
17,Leicester,38,6,7,25,33,80,25,38.058101,35.774607,85.887374,82.842694,-47.068087,13.248424,10.760771,159,381,26.4303
18,Ipswich,38,4,10,24,36,82,22,40.420593,38.898255,83.732644,79.165634,-40.267379,14.197644,8.973778,132,373,28.4466
19,Southampton,38,2,6,30,26,86,12,38.631216,36.922768,98.347608,91.389668,-54.466900,12.041237,10.962806,179,398,22.6856

### 팀 내 순위 보기

In [16]:
team_data = us.scrape_all_teams_data("2025/2026", "EPL", as_df=True)

2025/2026 EPL teams: 100%|██████████| 20/20 [00:14<00:00,  1.42it/s]

In [17]:
team_data.keys()

dict_keys(['https://understat.com/team/Aston_Villa/2025', 'https://understat.com/team/Everton/2025', 'https://understat.com/team/Bournemouth/2025', 'https://understat.com/team/Sunderland/2025', 'https://understat.com/team/Crystal_Palace/2025', 'https://understat.com/team/Chelsea/2025', 'https://understat.com/team/West_Ham/2025', 'https://understat.com/team/Tottenham/2025', 'https://understat.com/team/Arsenal/2025', 'https://understat.com/team/Newcastle_United/2025', 'https://understat.com/team/Liverpool/2025', 'https://understat.com/team/Manchester_City/2025', 'https://understat.com/team/Manchester_United/2025', 'https://understat.com/team/Burnley/2025', 'https://understat.com/team/Brighton/2025', 'https://understat.com/team/Fulham/2025', 'https://understat.com/team/Wolverhampton_Wanderers/2025', 'https://understat.com/team/Brentford/2025', 'https://understat.com/team/Leeds/2025', 'https://understat.com/team/Nottingham_Forest/2025'])

In [18]:
team_data['https://understat.com/team/Everton/2025'].keys()

dict_keys(['matches', 'team_data', 'players_data'])

In [19]:
team_data['https://understat.com/team/Everton/2025']['players_data'].head()

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,9307,Iliman Ndiaye,3,246,2,1.2893720269203186,0,0.12135979533195496,3,3,0,0,M,Everton,2,1.2893720269203186,2.108072556555271,0.69734076410532
1,7438,James Garner,3,270,1,0.07517694309353828,0,0.12179193645715714,3,2,1,0,D M,Everton,1,0.07517694309353828,0.9182510375976562,0.7808599770069122
2,9739,Kiernan Dewsbury-Hall,3,270,1,0.13513396680355072,1,1.6621424928307533,1,7,2,0,M,Everton,1,0.13513396680355072,1.6774157881736755,1.4157174229621887
3,9983,Beto,3,193,1,0.8489327803254128,0,0.10769732296466827,3,1,1,0,F S,Everton,1,0.8489327803254128,1.4627134054899216,0.5479457378387451
4,585,Seamus Coleman,1,1,0,0,0,0,0,0,0,0,S,Everton,0,0,0,0

### 경기 정보 보기

In [20]:
us_match = us.scrape_match(us_match_links[0], as_df=False)

In [21]:
us_match[0].keys() #home away 구분

dict_keys(['h', 'a'])

In [22]:
us_match_df = pd.DataFrame(us_match[0]['h']) # 첫번째 경기의 홈 팀 정보

In [23]:
us_match_df.head()

,id,minute,result,X,Y,xG,player,h_a,player_id,situation,season,shotType,match_id,h_team,a_team,h_goals,a_goals,date,player_assisted,lastAction
0,637500,2,SavedShot,0.7619999694824219,0.6990000152587891,0.014601008035242558,Hugo Ekitike,h,8995,OpenPlay,2025,RightFoot,28778,Liverpool,Bournemouth,4,2,2025-08-15 19:00:00,Cody Gakpo,Pass
1,637501,3,SavedShot,0.855999984741211,0.3129999923706055,0.04265604913234711,Mohamed Salah,h,1250,OpenPlay,2025,LeftFoot,28778,Liverpool,Bournemouth,4,2,2025-08-15 19:00:00,Hugo Ekitike,Pass
2,637502,4,MissedShots,0.914000015258789,0.505,0.25797542929649353,Virgil van Dijk,h,833,FromCorner,2025,Head,28778,Liverpool,Bournemouth,4,2,2025-08-15 19:00:00,Mohamed Salah,Cross
3,637505,30,SavedShot,0.9119999694824219,0.5320000076293945,0.0776621475815773,Virgil van Dijk,h,833,FromCorner,2025,Head,28778,Liverpool,Bournemouth,4,2,2025-08-15 19:00:00,Florian Wirtz,Cross
4,637507,36,Goal,0.8909999847412109,0.524000015258789,0.40409132838249207,Hugo Ekitike,h,8995,OpenPlay,2025,RightFoot,28778,Liverpool,Bournemouth,4,2,2025-08-15 19:00:00,Alexis Mac Allister,TakeOn

### 여러 경기 보기

In [24]:
us_matches = us.scrape_matches('2025/2026', 'EPL', as_df=False)

2025/2026 EPL matches: 100%|██████████| 30/30 [00:18<00:00,  1.59it/s]

In [25]:
us_matches.keys()

dict_keys(['https://understat.com/match/28778', 'https://understat.com/match/28779', 'https://understat.com/match/28780', 'https://understat.com/match/28781', 'https://understat.com/match/28782', 'https://understat.com/match/28783', 'https://understat.com/match/28784', 'https://understat.com/match/28785', 'https://understat.com/match/28786', 'https://understat.com/match/28787', 'https://understat.com/match/28788', 'https://understat.com/match/28789', 'https://understat.com/match/28790', 'https://understat.com/match/28791', 'https://understat.com/match/28792', 'https://understat.com/match/28793', 'https://understat.com/match/28794', 'https://understat.com/match/28795', 'https://understat.com/match/28796', 'https://understat.com/match/28797', 'https://understat.com/match/28798', 'https://understat.com/match/28799', 'https://understat.com/match/28800', 'https://understat.com/match/28801', 'https://understat.com/match/28802', 'https://understat.com/match/28803', 'https://understat.com/match/28804', 'https://understat.com/match/28805', 'https://understat.com/match/28806', 'https://understat.com/match/28807'])

In [26]:
pd.DataFrame(us_matches['https://understat.com/match/28778'])

,shots_data,match_info,rosters_data
h,"[{'id': '637500', 'minute': '2', 'result': 'Sa...",87,"{'731570': {'id': '731570', 'goals': '0', 'own..."
a,"[{'id': '637503', 'minute': '5', 'result': 'Mi...",73,"{'731586': {'id': '731586', 'goals': '0', 'own..."
id,NaN,28778,NaN
fid,NaN,1903117,NaN
date,NaN,2025-08-15 19:00:00,NaN
league_id,NaN,1,NaN
season,NaN,2025,NaN
h_goals,NaN,4,NaN
a_goals,NaN,2,NaN
team_h,NaN,Liverpool,NaN
team_a,NaN,Bournemouth,NaN
h_xg,NaN,2.33007,NaN
a_xg,NaN,1.57303,NaN
h_w,NaN,0.5498,NaN
h_d,NaN,0.2276,NaN
h_l,NaN,0.2226,NaN
league,NaN,EPL,NaN
h_shot,NaN,19,NaN
a_shot,NaN,10,NaN
h_shotOnTarget,NaN,10,NaN
a_shotOnTarget,NaN,3,NaN
h_deep,NaN,9,NaN
a_deep,NaN,8,NaN
a_ppda,NaN,11.5833,NaN
h_ppda,NaN,8.7647,NaN

### 시즌 누적 데이터 불러오기

In [27]:
us_season_data = us.scrape_season_data('2025/2026', 'EPL')

In [28]:
pd.DataFrame(us_season_data[2])

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,8260,Erling Haaland,3,258,3,3.6530365645885468,0,0.36525797843933105,14,1,0,0,F,Manchester City,3,3.6530365645885468,3.180346816778183,0.10486970096826553
1,4456,Chris Wood,3,246,2,1.0468871891498566,0,0.09181983023881912,7,1,0,0,F,Nottingham Forest,2,1.0468871891498566,1.160836011171341,0.10880379006266594
2,5675,Ismaila Sarr,3,270,2,1.9466686844825745,0,0.025558898225426674,3,1,1,0,F M,Crystal Palace,2,1.9466686844825745,2.30912783741951,0.3369002975523472
3,6026,Richarlison,3,248,2,0.9355672523379326,1,0.4369896538555622,8,2,1,0,F,Tottenham,2,0.9355672523379326,2.2818097956478596,0.926425576210022
4,7148,Wilson Isidor,3,60,2,0.4166402667760849,0,0,4,0,0,0,S,Sunderland,2,0.4166402667760849,0.5288994461297989,0.12492907047271729
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,13780,Antoni Milambo,1,50,0,0,0,0,0,0,0,0,M,Brentford,0,0,0.043761223554611206,0.043761223554611206
366,13834,Ao Tanaka,2,151,0,0.1117604449391365,0,0.08181378990411758,2,2,0,0,M,Leeds,0,0.1117604449391365,0.33549945801496506,0.14192520827054977
367,13835,Joël Piroe,2,139,0,0.5239394903182983,0,0,3,0,0,0,F,Leeds,0,0.5239394903182983,0.5803539082407951,0.05641444772481918
368,13870,Bradley Burrowes,1,12,0,0,0,0,0,0,0,0,S,Aston Villa,0,0,0,0
369,13872,Max Dowman,2,24,0,0.15431709215044975,0,0,3,0,0,0,S,Arsenal,0,0.15431709215044975,0.12994308397173882,0

### 특정 팀의 경기 데이터 불러오기

In [29]:
us_team_data = us.scrape_team_data(us_team_links[0], as_df=False) # 특정 팀(aston villa)의 팀 데이터 불러오기

In [30]:
pd.DataFrame(us_team_data[2]) # 일정, 공격 진행 통계, 팀 내 순위

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,1024,Tyrone Mings,3,270,0,0.12713322043418884,0,0.10142877697944641,2,1,0,0,D,Aston Villa,0,0.12713322043418884,1.0677927657961845,0.9244915768504143
1,1823,Lucas Digne,3,165,0,0,0,0,0,0,0,0,D S,Aston Villa,0,0,0.01685994677245617,0.01685994677245617
2,2203,Emiliano Buendía,2,108,0,0.1429617516696453,0,0.2618386968970299,3,4,0,0,S,Aston Villa,0,0.1429617516696453,0.527164489030838,0.2330026775598526
3,4401,Emiliano Martinez,1,90,0,0,0,0,0,0,0,0,GK,Aston Villa,0,0,0.2738601565361023,0.2738601565361023
4,5789,Boubacar Kamara,2,105,0,0.17516101896762848,0,0,1,0,1,0,M,Aston Villa,0,0.17516101896762848,0.06348427385091782,0.06348427385091782
5,5956,Youri Tielemans,3,270,0,0.1518993116915226,0,0.14734115079045296,5,4,0,0,M,Aston Villa,0,0.1518993116915226,0.7420355901122093,0.659475289285183
6,6221,Pau Torres,2,102,0,0.06733081489801407,0,0,1,0,0,0,D S,Aston Villa,0,0.06733081489801407,0.4005170464515686,0.33318620920181274
7,7723,John McGinn,3,244,0,0.04055987671017647,0,0.642275620251894,1,4,0,0,M,Aston Villa,0,0.04055987671017647,0.86923548579216,0.8193352520465851
8,7726,Ezri Konsa Ngoyo,2,156,0,0,0,0.04962930828332901,0,1,0,1,D,Aston Villa,0,0,0.7131771445274353,0.6635478734970093
9,8006,Evann Guessand,2,57,0,0.06263919174671173,0,0,1,0,0,0,M S,Aston Villa,0,0.06263919174671173,0.11798285692930222,0.055343665182590485
10,8864,Matthew Cash,3,258,0,0.01937158778309822,0,0.24263860285282135,1,3,1,0,D,Aston Villa,0,0.01937158778309822,1.0412079617381096,0.8730824068188667
11,8865,Ollie Watkins,3,270,0,0.9710016176104546,0,0.20706670731306076,8,3,0,0,F,Aston Villa,0,0.9710016176104546,1.2556147128343582,0.07754640281200409
12,9614,Marco Bizot,2,180,0,0,0,0,0,0,1,0,GK,Aston Villa,0,0,0.5747163221240044,0.5747163221240044
13,9667,Amadou Onana,2,162,0,0.09780319035053253,0,0,2,0,1,0,M,Aston Villa,0,0.09780319035053253,0.2444225177168846,0.14661933481693268
14,9749,Donyell Malen,3,111,0,0.37130817025899887,0,0,3,0,0,0,M S,Aston Villa,0,0.37130817025899887,0.49756132811307907,0.1262531578540802
15,10025,Lamare Bogarde,2,10,0,0,0,0,0,0,1,0,S,Aston Villa,0,0,0,0
16,11807,Ian Maatsen,2,106,0,0.09806197881698608,0,0.13109983503818512,2,3,0,0,D S,Aston Villa,0,0.09806197881698608,0.20740310102701187,0.12985669821500778
17,12412,Morgan Rogers,3,270,0,0.20143605023622513,0,0.16907917708158493,3,2,0,0,M,Aston Villa,0,0.20143605023622513,0.5984575301408768,0.2279423177242279
18,13870,Bradley Burrowes,1,12,0,0,0,0,0,0,0,0,S,Aston Villa,0,0,0,0